//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.09 at 04:52:32 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.eidiko.com/soap/country", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.eidiko.soap.country;
